# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-advanced3-4

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Check Azure Web App existence
        run: |
          echo "Checking if Azure Web App exists..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://app-advanced3-4-aygnfjh3hxbyducf.canadacentral-01.azurewebsites.net)
          if [ $response -eq 404 ]; then
            echo "Warning: Azure Web App returned 404. Proceeding with deployment..."
          fi
      - name: npm install and build
        run: |
          npm ci  # Changed to npm ci for cleaner installs
          npm run build --if-present
        env:
          CI: true

      - name: Run tests
        run: npm run test --if-present
        continue-on-error: true

      - name: Prepare artifact
        run: |
          # Remove unnecessary files before zipping
          rm -rf node_modules/
          rm -rf .git/
          rm -f *.log

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-advanced3-4'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_71149E3108424F929BFD6EDA9290D0B0 }}
